// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/clientInterfaces.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	models "home_automation/internal/models"
	utils "home_automation/internal/utils"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	knx "github.com/vapourismo/knx-go/knx"
)

// MockIBricksClientInterface is a mock of IBricksClientInterface interface.
type MockIBricksClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIBricksClientInterfaceMockRecorder
}

// MockIBricksClientInterfaceMockRecorder is the mock recorder for MockIBricksClientInterface.
type MockIBricksClientInterfaceMockRecorder struct {
	mock *MockIBricksClientInterface
}

// NewMockIBricksClientInterface creates a new mock instance.
func NewMockIBricksClientInterface(ctrl *gomock.Controller) *MockIBricksClientInterface {
	mock := &MockIBricksClientInterface{ctrl: ctrl}
	mock.recorder = &MockIBricksClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBricksClientInterface) EXPECT() *MockIBricksClientInterfaceMockRecorder {
	return m.recorder
}

// SetMemo mocks base method.
func (m *MockIBricksClientInterface) SetMemo(memoName string, memoValue interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMemo", memoName, memoValue)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMemo indicates an expected call of SetMemo.
func (mr *MockIBricksClientInterfaceMockRecorder) SetMemo(memoName, memoValue interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMemo", reflect.TypeOf((*MockIBricksClientInterface)(nil).SetMemo), memoName, memoValue)
}

// StartSendingHeartbeat mocks base method.
func (m *MockIBricksClientInterface) StartSendingHeartbeat(frequency int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartSendingHeartbeat", frequency)
}

// StartSendingHeartbeat indicates an expected call of StartSendingHeartbeat.
func (mr *MockIBricksClientInterfaceMockRecorder) StartSendingHeartbeat(frequency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSendingHeartbeat", reflect.TypeOf((*MockIBricksClientInterface)(nil).StartSendingHeartbeat), frequency)
}

// TriggerShutterPosition mocks base method.
func (m *MockIBricksClientInterface) TriggerShutterPosition() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerShutterPosition")
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerShutterPosition indicates an expected call of TriggerShutterPosition.
func (mr *MockIBricksClientInterfaceMockRecorder) TriggerShutterPosition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerShutterPosition", reflect.TypeOf((*MockIBricksClientInterface)(nil).TriggerShutterPosition))
}

// MockMeteoClientInterface is a mock of MeteoClientInterface interface.
type MockMeteoClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMeteoClientInterfaceMockRecorder
}

// MockMeteoClientInterfaceMockRecorder is the mock recorder for MockMeteoClientInterface.
type MockMeteoClientInterfaceMockRecorder struct {
	mock *MockMeteoClientInterface
}

// NewMockMeteoClientInterface creates a new mock instance.
func NewMockMeteoClientInterface(ctrl *gomock.Controller) *MockMeteoClientInterface {
	mock := &MockMeteoClientInterface{ctrl: ctrl}
	mock.recorder = &MockMeteoClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeteoClientInterface) EXPECT() *MockMeteoClientInterfaceMockRecorder {
	return m.recorder
}

// GetWindDirection mocks base method.
func (m *MockMeteoClientInterface) GetWindDirection() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWindDirection")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetWindDirection indicates an expected call of GetWindDirection.
func (mr *MockMeteoClientInterfaceMockRecorder) GetWindDirection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWindDirection", reflect.TypeOf((*MockMeteoClientInterface)(nil).GetWindDirection))
}

// GetWindDirectionFactor mocks base method.
func (m *MockMeteoClientInterface) GetWindDirectionFactor() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWindDirectionFactor")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetWindDirectionFactor indicates an expected call of GetWindDirectionFactor.
func (mr *MockMeteoClientInterfaceMockRecorder) GetWindDirectionFactor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWindDirectionFactor", reflect.TypeOf((*MockMeteoClientInterface)(nil).GetWindDirectionFactor))
}

// StratFetchingWindStatus mocks base method.
func (m *MockMeteoClientInterface) StratFetchingWindStatus() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StratFetchingWindStatus")
}

// StratFetchingWindStatus indicates an expected call of StratFetchingWindStatus.
func (mr *MockMeteoClientInterfaceMockRecorder) StratFetchingWindStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StratFetchingWindStatus", reflect.TypeOf((*MockMeteoClientInterface)(nil).StratFetchingWindStatus))
}

// MockPromClientInterface is a mock of PromClientInterface interface.
type MockPromClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPromClientInterfaceMockRecorder
}

// MockPromClientInterfaceMockRecorder is the mock recorder for MockPromClientInterface.
type MockPromClientInterfaceMockRecorder struct {
	mock *MockPromClientInterface
}

// NewMockPromClientInterface creates a new mock instance.
func NewMockPromClientInterface(ctrl *gomock.Controller) *MockPromClientInterface {
	mock := &MockPromClientInterface{ctrl: ctrl}
	mock.recorder = &MockPromClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPromClientInterface) EXPECT() *MockPromClientInterfaceMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockPromClientInterface) Query(metric string) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", metric)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPromClientInterfaceMockRecorder) Query(metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPromClientInterface)(nil).Query), metric)
}

// MockKnxClientInterface is a mock of KnxClientInterface interface.
type MockKnxClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKnxClientInterfaceMockRecorder
}

// MockKnxClientInterfaceMockRecorder is the mock recorder for MockKnxClientInterface.
type MockKnxClientInterfaceMockRecorder struct {
	mock *MockKnxClientInterface
}

// NewMockKnxClientInterface creates a new mock instance.
func NewMockKnxClientInterface(ctrl *gomock.Controller) *MockKnxClientInterface {
	mock := &MockKnxClientInterface{ctrl: ctrl}
	mock.recorder = &MockKnxClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKnxClientInterface) EXPECT() *MockKnxClientInterfaceMockRecorder {
	return m.recorder
}

// SendMessageToKnx mocks base method.
func (m *MockKnxClientInterface) SendMessageToKnx(destination string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessageToKnx", destination, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessageToKnx indicates an expected call of SendMessageToKnx.
func (mr *MockKnxClientInterfaceMockRecorder) SendMessageToKnx(destination, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessageToKnx", reflect.TypeOf((*MockKnxClientInterface)(nil).SendMessageToKnx), destination, data)
}

// MockShellyClientInterface is a mock of ShellyClientInterface interface.
type MockShellyClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockShellyClientInterfaceMockRecorder
}

// MockShellyClientInterfaceMockRecorder is the mock recorder for MockShellyClientInterface.
type MockShellyClientInterfaceMockRecorder struct {
	mock *MockShellyClientInterface
}

// NewMockShellyClientInterface creates a new mock instance.
func NewMockShellyClientInterface(ctrl *gomock.Controller) *MockShellyClientInterface {
	mock := &MockShellyClientInterface{ctrl: ctrl}
	mock.recorder = &MockShellyClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShellyClientInterface) EXPECT() *MockShellyClientInterfaceMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockShellyClientInterface) GetStatus(actor *models.ShellyDevice) (*models.ShellyGetStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", actor)
	ret0, _ := ret[0].(*models.ShellyGetStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockShellyClientInterfaceMockRecorder) GetStatus(actor interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockShellyClientInterface)(nil).GetStatus), actor)
}

// HandleFullStatusMessageMessage mocks base method.
func (m *MockShellyClientInterface) HandleFullStatusMessageMessage(message *models.ShellyStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleFullStatusMessageMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleFullStatusMessageMessage indicates an expected call of HandleFullStatusMessageMessage.
func (mr *MockShellyClientInterfaceMockRecorder) HandleFullStatusMessageMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleFullStatusMessageMessage", reflect.TypeOf((*MockShellyClientInterface)(nil).HandleFullStatusMessageMessage), message)
}

// HandleKnxMessage mocks base method.
func (m *MockShellyClientInterface) HandleKnxMessage(knxAddr string, msg knx.GroupEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleKnxMessage", knxAddr, msg)
}

// HandleKnxMessage indicates an expected call of HandleKnxMessage.
func (mr *MockShellyClientInterfaceMockRecorder) HandleKnxMessage(knxAddr, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleKnxMessage", reflect.TypeOf((*MockShellyClientInterface)(nil).HandleKnxMessage), knxAddr, msg)
}

// HandleStatusMessage mocks base method.
func (m *MockShellyClientInterface) HandleStatusMessage(message *models.ShellyStatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleStatusMessage", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleStatusMessage indicates an expected call of HandleStatusMessage.
func (mr *MockShellyClientInterfaceMockRecorder) HandleStatusMessage(message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleStatusMessage", reflect.TypeOf((*MockShellyClientInterface)(nil).HandleStatusMessage), message)
}

// HandleWebSocketMessage mocks base method.
func (m *MockShellyClientInterface) HandleWebSocketMessage(messageContent []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleWebSocketMessage", messageContent)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleWebSocketMessage indicates an expected call of HandleWebSocketMessage.
func (mr *MockShellyClientInterfaceMockRecorder) HandleWebSocketMessage(messageContent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebSocketMessage", reflect.TypeOf((*MockShellyClientInterface)(nil).HandleWebSocketMessage), messageContent)
}

// SetRelaisValue mocks base method.
func (m *MockShellyClientInterface) SetRelaisValue(actor *models.ShellyDevice, value bool) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRelaisValue", actor, value)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetRelaisValue indicates an expected call of SetRelaisValue.
func (mr *MockShellyClientInterfaceMockRecorder) SetRelaisValue(actor, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRelaisValue", reflect.TypeOf((*MockShellyClientInterface)(nil).SetRelaisValue), actor, value)
}

// StartFetchShellyData mocks base method.
func (m *MockShellyClientInterface) StartFetchShellyData(ctx context.Context, gauges utils.PromExporterGauges, frequency int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartFetchShellyData", ctx, gauges, frequency)
}

// StartFetchShellyData indicates an expected call of StartFetchShellyData.
func (mr *MockShellyClientInterfaceMockRecorder) StartFetchShellyData(ctx, gauges, frequency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFetchShellyData", reflect.TypeOf((*MockShellyClientInterface)(nil).StartFetchShellyData), ctx, gauges, frequency)
}
