// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/monitorInterfaces.go

// Package mock_interfaces is a generated GoMock package.
package mock_interfaces

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockWeatherMonitorInterface is a mock of WeatherMonitorInterface interface.
type MockWeatherMonitorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherMonitorInterfaceMockRecorder
}

// MockWeatherMonitorInterfaceMockRecorder is the mock recorder for MockWeatherMonitorInterface.
type MockWeatherMonitorInterfaceMockRecorder struct {
	mock *MockWeatherMonitorInterface
}

// NewMockWeatherMonitorInterface creates a new mock instance.
func NewMockWeatherMonitorInterface(ctrl *gomock.Controller) *MockWeatherMonitorInterface {
	mock := &MockWeatherMonitorInterface{ctrl: ctrl}
	mock.recorder = &MockWeatherMonitorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherMonitorInterface) EXPECT() *MockWeatherMonitorInterfaceMockRecorder {
	return m.recorder
}

// CheckWindClassChange mocks base method.
func (m *MockWeatherMonitorInterface) CheckWindClassChange(windspeed float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckWindClassChange", windspeed)
}

// CheckWindClassChange indicates an expected call of CheckWindClassChange.
func (mr *MockWeatherMonitorInterfaceMockRecorder) CheckWindClassChange(windspeed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckWindClassChange", reflect.TypeOf((*MockWeatherMonitorInterface)(nil).CheckWindClassChange), windspeed)
}

// StartFetchingMaxWindspeed mocks base method.
func (m *MockWeatherMonitorInterface) StartFetchingMaxWindspeed(ctx context.Context, frequency int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "StartFetchingMaxWindspeed", ctx, frequency)
}

// StartFetchingMaxWindspeed indicates an expected call of StartFetchingMaxWindspeed.
func (mr *MockWeatherMonitorInterfaceMockRecorder) StartFetchingMaxWindspeed(ctx, frequency interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartFetchingMaxWindspeed", reflect.TypeOf((*MockWeatherMonitorInterface)(nil).StartFetchingMaxWindspeed), ctx, frequency)
}
